### ISSUE TITLE
Requests fails with 500 Server Error if OMBI >4256

### ISSUE THREAD

**Issue by yplin0623** [StackTraceYo/plex-bot#15]
All requests failed with a 500 server error after upgrading OMBI. 

Reverted back to 4256 and it worked again.

Not sure if the problem is with ombi or ombi-bot.

**Comment by StackTraceYo** [comment]
Will take a look. Might be with Ombi

**Comment by StackTraceYo** [comment]
are you using the docker or jar

**Comment by StackTraceYo** [comment]
@yplin0623 try the 1.2-SNAPSHOT docker

**Comment by crxo1** [comment]
Hi, same error here with Ombi version 3.0.4680 and the 1.2 Docker image.

**Comment by StackTraceYo** [comment]
@crxo1 is this still an issue. I just released 2.0. can you try that if not i can take a look

**Comment by StackTraceYo** [comment]
I believe this is fixed as of 2.0
