### ISSUE TITLE
"Request" button doesn't do anything (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by ghost** [StackTraceYo/plex-bot#17]
Hi!

I'm using a Docker container on my Synology NAS to run Ombi-bot. There's no issue to search any media but the "Request" button in the Telegram's bot doesn't do anything.

Here's the container's logs just after click on "request" button:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/31062488/66653839-318b1400-ec39-11e9-94a5-53e884f1adca.png">

Hope you could help me!

Any idea @StackTraceYo ?

**Comment by StackTraceYo** [comment]
Can you post more of the log

**Comment by ghost** [comment]
Sure, here's my full log since I've made the search of the movie: https://paste.ofcode.org/XQJCL9PfjzPR3FKptUmqHY

**Comment by StackTraceYo** [comment]
What version of ombi are you using

**Comment by ghost** [comment]
3.0.4680

**Comment by StackTraceYo** [comment]
I will have to bump my version I use and see whats up.
I am using - Version | 3.0.4256

**Comment by StackTraceYo** [comment]
I pushed a snapshot version stacktraceyo/ombi-bot:1.2-SNAPSHOT.

can you try that with your version?

heres what is in it:  https://github.com/StackTraceYo/ombi-bot/commits/1.2

it has imdb id search, removal of requests when they are completed, and a username workaround.

the bot.env now has a new parameter that OMBI_USER_NAME parameter that you should provide as the admin account for the ombi. If you dont provide it it should use the ApiAlias which according to the ombi docs should work but it wasnt some time ago. I opened a ticket with them ill have to check the status.

Im still planning on upgrading my ombi and testing - but try the new image I pushed and see if it helps.

**Comment by ghost** [comment]
I can't run the container with the new image, there's an issue:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/31062488/66990328-4565c880-f0c6-11e9-8cbe-bd4cb4b68dba.png">
<img width="265" alt="image" src="https://user-images.githubusercontent.com/31062488/66990343-4c8cd680-f0c6-11e9-8460-76f7f5794d56.png">

Seems like it's about your image because no problem with others.

**Comment by StackTraceYo** [comment]
looks like the upstream java that the image uses changed where java should be ran from. fixing now

**Comment by StackTraceYo** [comment]
ok I pushed a new image try the 1.2-SNAPSHOT image now

**Comment by ghost** [comment]
Works fine now, thanks!

Just a little request because I check the log: there's some information about the media wanted (like release year, full title, little description), why not show this when searching with the bot? It could help.
Other "issue": when I'm searching a film from a saga (for example /searchmovie zombieland), it will show me "Movie has already been requested." because I already add the first, but not the second (it's not "zombieland 2"). So I can't add the second one because I don't have the exact name.

**Comment by StackTraceYo** [comment]
sure -  make another ticket and describe it in there
