### ISSUE TITLE
Suggestions to improve search

### ISSUE THREAD

**Issue by ghost** [StackTraceYo/plex-bot#18]
Hi!

I was using a Telegram bot to add movies to Radarr but it's easier for me to use the Ombi one (because I only use Ombi to manage this).

Here's what it looks like:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/31062488/67033799-c482ed00-f116-11e9-8557-505492d23607.png">

Interesting point : it show me complete name, year of release and every movie with my request in the title, even if I already have them in Radarr. No need to write the complete name

Here's with Ombi-bot:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/31062488/67033904-f6944f00-f116-11e9-8b92-7c348b4f1dc2.png">

Just the picture. Don't know if it's the first or second film.

And if if it's already been requested:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/31062488/67033951-1166c380-f117-11e9-8b99-4ae77a28ca3f.png">

So if I want to add "zombieland 2" but without knowing the exact name, I can't.

I hope you can do something to improve the UX, that could be difficult to select the good movie.

**Comment by StackTraceYo** [comment]
2.0

**Comment by StackTraceYo** [comment]
i changed the search behavior, in the new version
