### ISSUE TITLE
Availability issue

### ISSUE THREAD

**Issue by lebnet** [StackTraceYo/plex-bot#22]
Hello,

when I ask the bot for a movie I have always "movie unavailable" even if the movie is available in ombi (and in Plex obvisouly.

Example : 
![Ombi db screen](https://i.imgur.com/7wkZPU7.png)

![Telegram chat screen](https://i.imgur.com/r6t0DnX.png)

Do you have any suggestions ?

**Comment by StackTraceYo** [comment]
I recently released 2.0. can you try the new version?

**Comment by lebnet** [comment]
I just made a docker pull request to update and restart my container and ask ombi to manually re-scan my plex library and same result from the bot "movie unavailable" :/

Maybe some time to update docker ombi-bot image ?

**Comment by StackTraceYo** [comment]
can you post some logs

**Comment by StackTraceYo** [comment]
make sure your machine identifier is correct.

**Comment by StackTraceYo** [comment]
If this comes up again let me know. Ive seen it happen when the machine identifier in ombi is mismatched with the server identifier. The server identifier is in the url. closing for now
