### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by tidusjar** [StackTraceYo/plex-bot#5]
Is this not a ombi-bot?

Or are you going to add more non-ombi features?

Just curious 😁

**Comment by StackTraceYo** [comment]
I was going to add more but I think it makes sense to have them as separate projects - i updates the repo

**Comment by tidusjar** [comment]
Let me know when it's in a stable state and maybe i'll add a link on the telegram page for you!

**Comment by StackTraceYo** [comment]
sure thing. that would be awesome.  

Also let me know If there are some features you think would be cool for the bot

**Comment by tidusjar** [comment]
Your best bet would be to ask on the discord ombi channel regarding
features
